name: selenium-tests

on:
  push:
    branches:
      - master  # adjust branch name if needed
  pull_request:
    branches:
      - master  # adjust branch name if needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Selenium Tests
        run: mvn test
