name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        browser: [chrome, firefox]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up WebDriver
      run: |
        if [ ${{ matrix.browser }} == 'chrome' ]; then
          wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/2.45/chromedriver_linux64.zip
          unzip /tmp/chromedriver.zip -d /tmp
          sudo mv /tmp/chromedriver /usr/local/bin/
        fi
        if [ ${{ matrix.browser }} == 'firefox' ]; then
          wget -q -O /tmp/geckodriver.tar.gz https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
          tar -xzf /tmp/geckodriver.tar.gz -C /tmp
          sudo mv /tmp/geckodriver /usr/local/bin/
        fi

    - name: Run Selenium Tests
      run: |
        if [ ${{ matrix.browser }} == 'chrome' ]; then
          mvn test -Dbrowser=chrome
        fi
        if [ ${{ matrix.browser }} == 'firefox' ]; then
          mvn test -Dbrowser=firefox
        fi
